# Generated by Django 6.1 on 2026-08-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_booking_rejection_reason_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pnr',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
