# Generated by Django 6.1 on 2026-08-20 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_booking_pnr_booking_ticket_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('BAHRAIN', 'Bahrain Oneway'), ('KSA', 'KSA One Way'), ('OMAN', 'Oman One Way'), ('UAE', 'UAE Oneway'), ('UMRAH', 'Umrah')], max_length=20)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('baggage', models.CharField(default='20+7 KG', max_length=50)),
                ('meal', models.CharField(default='No', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_seats', models.PositiveIntegerField(default=0)),
                ('available_seats', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_tickets', to='website.airline')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_ticket_arrivals', to='website.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_ticket_departures', to='website.airport')),
            ],
        ),
    ]
