# Generated by Django 6.1 on 2026-08-21 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_groupticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(max_length=30, unique=True)),
                ('seats_booked', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_bookings', to='website.agent')),
                ('group_ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_bookings', to='website.groupticket')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_bookings', to='website.passenger')),
            ],
        ),
    ]
