# Generated by Django 6.1 on 2026-08-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_groupbooking_confirmed_at_groupbooking_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agency_logo',
            field=models.ImageField(blank=True, null=True, upload_to='agency_logos/'),
        ),
    ]
