# Generated by Django 6.1 on 2026-08-25 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_agentwallet_topuprequest_wallettransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(choices=[('MAKKAH', 'Makkah'), ('MADINAH', 'Madinah')], max_length=20)),
                ('distance_from_reference', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='umrah_hotels/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['location', 'name'],
            },
        ),
        migrations.AddField(
            model_name='airline',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='airlines/'),
        ),
        migrations.CreateModel(
            name='UmrahPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Umrah Package', max_length=150)),
                ('sector', models.CharField(default='LHE-JED-LHE', max_length=50)),
                ('nights_in_makkah', models.PositiveIntegerField(default=0)),
                ('nights_in_madinah', models.PositiveIntegerField(default=0)),
                ('room_type', models.CharField(choices=[('SHARING', 'Sharing'), ('QUAD', 'Quad Sharing'), ('TRIPLE', 'Triple'), ('DOUBLE', 'Double'), ('SINGLE', 'Single')], default='SHARING', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_seats', models.PositiveIntegerField(default=0)),
                ('available_seats', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SOLD_OUT', 'Sold Out')], default='ACTIVE', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('madinah_hotel', models.ForeignKey(limit_choices_to={'location': 'MADINAH'}, on_delete=django.db.models.deletion.PROTECT, related_name='madinah_umrah_packages', to='website.hotel')),
                ('makkah_hotel', models.ForeignKey(limit_choices_to={'location': 'MAKKAH'}, on_delete=django.db.models.deletion.PROTECT, related_name='makkah_umrah_packages', to='website.hotel')),
                ('outbound_flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='umrah_outbound_packages', to='website.flight')),
                ('return_flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='umrah_return_packages', to='website.flight')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UmrahBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(max_length=30, unique=True)),
                ('pilgrims_count', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umrah_bookings', to='website.agent')),
                ('lead_passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_umrah_bookings', to='website.passenger')),
                ('pilgrims', models.ManyToManyField(blank=True, related_name='umrah_bookings', to='website.passenger')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='website.umrahpackage')),
            ],
        ),
    ]
