# Generated by Django 6.1 on 2026-08-25 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_hotel_airline_logo_umrahpackage_umrahbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umrahpackage',
            name='outbound_flight',
        ),
        migrations.RemoveField(
            model_name='umrahpackage',
            name='return_flight',
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='airline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='umrah_packages', to='website.airline'),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='outbound_arrival_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='umrah_outbound_arrivals', to='website.airport'),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='outbound_arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='outbound_baggage',
            field=models.CharField(default='20+7 KG', max_length=50),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='outbound_departure_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='umrah_outbound_departures', to='website.airport'),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='outbound_departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='outbound_departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='outbound_flight_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='outbound_meal',
            field=models.CharField(default='No', max_length=50),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='return_arrival_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='umrah_return_arrivals', to='website.airport'),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='return_arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='return_baggage',
            field=models.CharField(default='20+7 KG', max_length=50),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='return_departure_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='umrah_return_departures', to='website.airport'),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='return_departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='return_departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='return_flight_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='return_meal',
            field=models.CharField(default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='umrahpackage',
            name='madinah_hotel',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'location': 'MADINAH'}, on_delete=django.db.models.deletion.PROTECT, related_name='madinah_umrah_packages', to='website.hotel'),
        ),
        migrations.AlterField(
            model_name='umrahpackage',
            name='makkah_hotel',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'location': 'MAKKAH'}, on_delete=django.db.models.deletion.PROTECT, related_name='makkah_umrah_packages', to='website.hotel'),
        ),
    ]
